name: ci-cd
on:
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: npm CI
        run: npm ci

      - name: npm Check
        run: npm run check

      - name: npm Test
        run: npm run test

      - name: npm Build
        run: BUILD_BRANCH=${{ github.event.pull_request.head.ref }} BUILD_COMMIT=${{ github.sha }} npm run build

      - name: Deploy S3 Development
        if: github.event_name == 'push' && github.event.pull_request.head.ref == 'AUT-1161'
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --cache-control max-age=31536000,public
        env:
          AWS_S3_BUCKET: 'aws-development-split-public'
          AWS_ACCESS_KEY_ID: ${{ secrets.NEW_STAGE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NEW_STAGE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './lib-umd'
          DEST_DIR: sdk

      - name: Deploy S3 Master
        if: github.event_name == 'push' && github.event.pull_request.head.ref == 'master'
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --cache-control max-age=31536000,public
        env:
          AWS_S3_BUCKET: 'split-public'
          AWS_ACCESS_KEY_ID: ${{ secrets.PUBLIC_ASSETS_PROD_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PUBLIC_ASSETS_PROD_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './lib-umd'
          DEST_DIR: sdk
